DROP TABLE Fish IF EXISTS;
DROP TABLE User IF EXISTS;
DROP TABLE Role IF EXISTS;
DROP TABLE Resources IF EXISTS;
DROP TABLE user_role IF EXISTS;
DROP TABLE role_resources IF EXISTS;
DROP TABLE Receipt IF EXISTS;

CREATE TABLE Fish (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  name VARCHAR(100) NOT NULL,
  image_url VARCHAR(200),
  description VARCHAR(1000),
  price DOUBLE NOT NULL,
  status VARCHAR(20),
  PRIMARY KEY (id)
);

CREATE TABLE Receipt (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL, 
  date_stamp VARCHAR(20) DEFAULT NULL, 
  description LONGVARCHAR, 
  category LONGVARCHAR, 
  cost decimal(10,2) DEFAULT NULL, 
  claim VARCHAR(10) DEFAULT NULL, 
  file_name VARCHAR(200) NOT NULL, 
  pre_cost decimal(10,2) DEFAULT '0.00' NOT NULL, 
  dollar_type VARCHAR(10) DEFAULT NULL, 
  image BINARY LARGE OBJECT, 
  thumbnail BINARY LARGE OBJECT, 
  rates decimal(10,2) DEFAULT '0.00' NOT NULL, --COMMENT 'exchange rates',
  PRIMARY KEY (id)
);

CREATE TABLE User (
  id integer NOT NULL PRIMARY KEY, 
  username VARCHAR(50) NOT NULL, 
  password VARCHAR(100) NOT NULL, 
  enable BOOLEAN NOT NULL
);

CREATE TABLE Role (
  id INTEGER NOT NULL PRIMARY KEY, 
  rolename VARCHAR(50) NOT NULL
);

CREATE TABLE Resources (
  id INTEGER NOT NULL PRIMARY KEY, 
  url VARCHAR(500) NOT NULL, 
  memo VARCHAR(50)
);

CREATE TABLE user_role (
  user_id INTEGER NOT NULL, 
  role_id INTEGER NOT NULL, 
  CONSTRAINT PK_UseRole PRIMARY KEY (user_id,role_id)
);

CREATE TABLE role_resources (
  role_id INTEGER NOT NULL, 
  resource_id INTEGER NOT NULL, 
  CONSTRAINT pk_roleresource PRIMARY KEY (role_id,resource_id)
);